#!/usr/bin/env/python
# 

K = random_link(12, num_components=1, initial_map_gives_link=True, simplify=False)

K.PD_code()
#[(16, 10, 17, 9), (12, 2, 13, 1), (14, 3, 15, 4), (6, 21, 7, 22), (20, 0, 21, 23), (5, 23, 6, 22), (13, 18, 14, 19), (10, 16, 11, 15), (11, 9, 12, 8), (4, 8, 5, 7), (2, 17, 3, 18), (19, 0, 20, 1)]
