#!/usr/bin/env/python
# 

K = random_link(3, num_components=1, initial_map_gives_link=True, simplify=False)

K.PD_code()
#[(0, 3, 1, 4), (2, 5, 3, 0), (4, 1, 5, 2)]

K = random_link(3, num_components=1, initial_map_gives_link=True, simplify=False)

K.PD_code()
#[(0, 3, 1, 4), (2, 5, 3, 0), (4, 1, 5, 2)]
